#pragma once

static const char template[] = {
    "#include <stdbool.h>\n"
    "#include <stdint.h>\n"
    "#define RV_NUM_REGS 32\n"
    "enum { INSN_16 = 2, INSN_32 = 4, };\n"
    "enum { rv_reg_zero = 0, };\n"
    "typedef void *riscv_user_t;\n"
    "typedef uint32_t riscv_word_t;\n"
    "typedef uint16_t riscv_half_t;\n"
    "typedef uint8_t riscv_byte_t;\n"
    "typedef uint32_t riscv_exception_t;\n"
    "typedef float riscv_float_t;\n"
    "typedef riscv_word_t (*riscv_mem_ifetch)(struct riscv_t *rv, riscv_word_t "
    "addr);\n"
    "typedef riscv_word_t (*riscv_mem_read_w)(struct riscv_t *rv, riscv_word_t "
    "addr);\n"
    "typedef riscv_half_t (*riscv_mem_read_s)(struct riscv_t *rv, riscv_word_t "
    "addr);\n"
    "typedef riscv_byte_t (*riscv_mem_read_b)(struct riscv_t *rv, riscv_word_t "
    "addr);\n"
    "typedef void (*riscv_mem_write_w)(struct riscv_t *rv,\n"
    "riscv_word_t addr,\n"
    "riscv_word_t data);\n"
    "typedef void (*riscv_mem_write_s)(struct riscv_t *rv,\n"
    "riscv_word_t addr,\n"
    "riscv_half_t data);\n"
    "typedef void (*riscv_mem_write_b)(struct riscv_t *rv,\n"
    "riscv_word_t addr,\n"
    "riscv_byte_t data);\n"
    "typedef void (*riscv_on_ecall)(struct riscv_t *rv);\n"
    "typedef void (*riscv_on_ebreak)(struct riscv_t *rv);\n"
    "struct riscv_io_t {\n"
    "riscv_mem_ifetch mem_ifetch;\n"
    "riscv_mem_read_w mem_read_w;\n"
    "riscv_mem_read_s mem_read_s;\n"
    "riscv_mem_read_b mem_read_b;\n"
    "riscv_mem_write_w mem_write_w;\n"
    "riscv_mem_write_s mem_write_s;\n"
    "riscv_mem_write_b mem_write_b;\n"
    "riscv_on_ecall on_ecall;\n"
    "riscv_on_ebreak on_ebreak;\n"
    "};\n"
    "struct riscv_t {\n"
    "bool halt;\n"
    "struct riscv_io_t io;\n"
    "riscv_word_t X[RV_NUM_REGS];\n"
    "riscv_word_t PC;\n"
    "riscv_user_t userdata;\n"
    "uint64_t csr_cycle;\n"
    "uint32_t csr_mstatus;\n"
    "uint32_t csr_mtvec;\n"
    "uint32_t csr_misa;\n"
    "uint32_t csr_mtval;\n"
    "uint32_t csr_mcause;\n"
    "uint32_t csr_mscratch;\n"
    "uint32_t csr_mepc;\n"
    "uint32_t csr_mip;\n"
    "uint32_t csr_mbadaddr;\n"
    "uint8_t insn_len;\n"
    "};\n"};