#include <stdio.h>
#include <string.h>

static int isspc(int c)
{
    return c == ' ' || c == '\t';
}

int main(int argc, char **argv)
{
    char l[1000], l2[1000], *p, *q;
    FILE *fp, *op;
    int c, e, cmt, cmt_n;

    if (argc < 3)
        return 1;

    fp = fopen(argv[1], "rb");
    op = fopen(argv[2], "wb");
    if (!fp || !op) {
        fprintf(stderr, "c2str: file error\n");
        return 1;
    }

    fprintf(op,
	    "/* Generated by %s. DO NOT EDIT */\n\n"
            "#pragma once\n"
            "static const char template[] = {\n", argv[1]);

    cmt = cmt_n = 0;
    for (;;) {
        p = l;

    append:
        if (fgets(p, sizeof l - (p - l), fp)) {
            p = strchr(p, 0);
            while (p > l && p[-1] <= ' ')
                --p;
            *p = 0;
        } else if (p == l)
            break;

        /* check for continuation */
        if (p > l && p[-1] == '\\') {
            p[-1] = ' ';
            goto append;
        }

        p = l, q = l2;
        /* count & skip leading spaces */
        while (*p && isspc(*p))
            ++p;

        /* handle comments */
        if (p[0] == '/' && cmt == 0) {
            if (p[1] == '*')
                cmt = 2;
            if (p[1] == '/')
                cmt = 1;
        }
        if (cmt) {
            fprintf(op, "%s", l);
            ++cmt_n;
            fprintf(op, "\n");
            if (cmt == 1)
                cmt = 0;
            if (cmt == 2) {
                p = strchr(l, 0);
                if (p >= l + 2 && p[-1] == '/' && p[-2] == '*')
                    cmt = 0;
            }
            continue;
        }

        /* output line as C string */
        e = 0;
        for (;;) {
            c = *p++;

            if (c == '/' && (p[0] == '/' || p[0] == '*'))
                c = 0; /* trailing comment detected */

            if (isspc(c)) {
                /* remove spaces if possible */
                if (q == l2 || isspc(q[-1]))
                    continue;
            }
            if (c == '(')
                ++e;
            if (c == ')')
                --e;
            if (c == '\\' || c == '\"')
                *q++ = '\\';
            *q++ = c;
            if (c == 0)
                break;
        }
        if (l2[0])
            fprintf(op, "    \"%s\\n\"\n", l2);
    }
    fprintf(op, "};\n");

    fclose(fp);
    fclose(op);
    return 0;
}
