/*
 * rv32emu is freely redistributable under the MIT License. See the file
 * "LICENSE" for information on usage and redistribution of this file.
 */

/* AUTO-GENERATED by gen-decoder.py from instructions.in — DO NOT EDIT */

#include <assert.h>
#include <stdlib.h>

#include "decode.h"
#include "riscv_private.h"

/* decode rd field: insn[11:7] */
static inline uint32_t decode_rd(const uint32_t insn)
{
    return (insn >> 7) & 0x1f;
}

/* decode rs1 field: insn[19:15] */
static inline uint32_t decode_rs1(const uint32_t insn)
{
    return (insn >> 15) & 0x1f;
}

/* decode rs2 field: insn[24:20] */
static inline uint32_t decode_rs2(const uint32_t insn)
{
    return (insn >> 20) & 0x1f;
}

/* decode funct3 field: insn[14:12] — only used by F-extension (rounding mode)
 */
#if RV32_HAS(EXT_F)
static inline uint32_t decode_funct3(const uint32_t insn)
{
    return (insn >> 12) & 0x7;
}
#endif /* RV32_HAS(EXT_F) */


/* I-type immediate: insn[31:20] sign-extended */
static inline int32_t decode_itype_imm(const uint32_t insn)
{
    return ((int32_t) (insn & 0xFFF00000)) >> 20;
}

/* S-type immediate: insn[31:25|11:7] sign-extended */
static inline int32_t decode_stype_imm(const uint32_t insn)
{
    uint32_t dst = 0;
    dst |= (insn & 0xFE000000);
    dst |= (insn & 0x00000F80) << 13;
    return ((int32_t) dst) >> 20;
}

/* B-type immediate: insn[31|7|30:25|11:8] sign-extended */
static inline int32_t decode_btype_imm(const uint32_t insn)
{
    uint32_t dst = 0;
    dst |= (insn & 0x80000000);
    dst |= (insn & 0x00000080) << 23;
    dst |= (insn & 0x7E000000) >> 1;
    dst |= (insn & 0x00000F00) << 12;
    return ((int32_t) dst) >> 19;
}

/* U-type immediate: insn[31:12] */
static inline uint32_t decode_utype_imm(const uint32_t insn)
{
    return insn & 0xFFFFF000;
}

/* J-type immediate: insn[31|19:12|20|30:21] sign-extended */
static inline int32_t decode_jtype_imm(const uint32_t insn)
{
    uint32_t dst = 0;
    dst |= (insn & 0x80000000);
    dst |= (insn & 0x000FF000) << 11;
    dst |= (insn & 0x00100000) << 2;
    dst |= (insn & 0x7FE00000) >> 9;
    return ((int32_t) dst) >> 11;
}

#if RV32_HAS(EXT_F)
/* R4-type rs3 field: insn[31:27] */
static inline uint32_t decode_r4type_rs3(const uint32_t insn)
{
    return (insn >> 27) & 0x1f;
}
#endif

/* decode I-type */
static inline void decode_itype(rv_insn_t *ir, const uint32_t insn)
{
    ir->imm = decode_itype_imm(insn);
    ir->rs1 = decode_rs1(insn);
    ir->rd = decode_rd(insn);
}

/* decode U-type */
static inline void decode_utype(rv_insn_t *ir, const uint32_t insn)
{
    ir->imm = decode_utype_imm(insn);
    ir->rd = decode_rd(insn);
}

/* decode S-type */
static inline void decode_stype(rv_insn_t *ir, const uint32_t insn)
{
    ir->imm = decode_stype_imm(insn);
    ir->rs2 = decode_rs2(insn);
    ir->rs1 = decode_rs1(insn);
}

/* decode R-type */
static inline void decode_rtype(rv_insn_t *ir, const uint32_t insn)
{
    ir->rs2 = decode_rs2(insn);
    ir->rs1 = decode_rs1(insn);
    ir->rd = decode_rd(insn);
}

/* decode B-type */
static inline void decode_btype(rv_insn_t *ir, const uint32_t insn)
{
    ir->imm = decode_btype_imm(insn);
    ir->rs2 = decode_rs2(insn);
    ir->rs1 = decode_rs1(insn);
}

/* decode J-type */
static inline void decode_jtype(rv_insn_t *ir, const uint32_t insn)
{
    ir->imm = decode_jtype_imm(insn);
    ir->rd = decode_rd(insn);
}

#if RV32_HAS(EXT_F)
/* decode R4-type */
static inline void decode_r4type(rv_insn_t *ir, const uint32_t insn)
{
    ir->rd = decode_rd(insn);
    ir->rs1 = decode_rs1(insn);
    ir->rs2 = decode_rs2(insn);
    ir->rs3 = decode_r4type_rs3(insn);
    ir->rm = decode_funct3(insn);
}
#endif

FORCE_INLINE bool csr_is_writable(const uint32_t csr)
{
    return csr < 0xc00;
}

static inline bool op_load(rv_insn_t *ir, const uint32_t insn)
{
    decode_itype(ir, insn);

    switch ((insn >> 12) & 0x7) {
    case 0:
        ir->opcode = rv_insn_lb;
        return true;
    case 1:
        ir->opcode = rv_insn_lh;
        return true;
    case 2:
        ir->opcode = rv_insn_lw;
        return true;
    case 4:
        ir->opcode = rv_insn_lbu;
        return true;
    case 5:
        ir->opcode = rv_insn_lhu;
        return true;
    default:
        break;
    }
    return false;
}

#if RV32_HAS(EXT_F)
static inline bool op_load_fp(rv_insn_t *ir, const uint32_t insn)
{
    decode_itype(ir, insn);

    switch ((insn >> 12) & 0x7) {
#if RV32_HAS(EXT_F)
    case 2:
        ir->opcode = rv_insn_flw;
        return true;
#endif /* RV32_HAS(EXT_F) */
    default:
        break;
    }
    return false;
}
#else /* !RV32_HAS(EXT_F) */
#define op_load_fp op_unimp
#endif /* RV32_HAS(EXT_F) */

static inline bool op_misc_mem(rv_insn_t *ir, const uint32_t insn)
{
    decode_rtype(ir, insn);

    switch ((insn >> 12) & 0x7) {
    case 0:
        ir->opcode = rv_insn_fence;
        return true;
#if RV32_HAS(Zifencei)
    case 1:
        ir->opcode = rv_insn_fencei;
        return true;
#endif /* RV32_HAS(Zifencei) */
    default:
        break;
    }
    return false;
}

static inline bool op_op_imm(rv_insn_t *ir, const uint32_t insn)
{
    decode_itype(ir, insn);

    /* Any integer computational instruction writing into "x0" is NOP. */
    if (unlikely(ir->rd == rv_reg_zero)) {
        ir->opcode = rv_insn_nop;
        return true;
    }

    switch ((insn >> 12) & 0x7) {
    case 0:
        ir->opcode = rv_insn_addi;
        return true;
    case 1:
        switch ((insn >> 20) & 0xfff) {
#if RV32_HAS(Zbb)
        case 0x600:
            ir->opcode = rv_insn_clz;
            return true;
#endif /* RV32_HAS(Zbb) */
#if RV32_HAS(Zbb)
        case 0x601:
            ir->opcode = rv_insn_ctz;
            return true;
#endif /* RV32_HAS(Zbb) */
#if RV32_HAS(Zbb)
        case 0x602:
            ir->opcode = rv_insn_cpop;
            return true;
#endif /* RV32_HAS(Zbb) */
#if RV32_HAS(Zbb)
        case 0x604:
            ir->opcode = rv_insn_sextb;
            return true;
#endif /* RV32_HAS(Zbb) */
#if RV32_HAS(Zbb)
        case 0x605:
            ir->opcode = rv_insn_sexth;
            return true;
#endif /* RV32_HAS(Zbb) */
        default:
            break;
        }
        switch ((insn >> 25) & 0x7f) {
        case 0:
            ir->opcode = rv_insn_slli;
            return true;
#if RV32_HAS(Zbs)
        case 0x14:
            ir->opcode = rv_insn_bseti;
            return true;
#endif /* RV32_HAS(Zbs) */
#if RV32_HAS(Zbs)
        case 0x24:
            ir->opcode = rv_insn_bclri;
            return true;
#endif /* RV32_HAS(Zbs) */
#if RV32_HAS(Zbs)
        case 0x34:
            ir->opcode = rv_insn_binvi;
            return true;
#endif /* RV32_HAS(Zbs) */
        default:
            break;
        }
        break;
    case 2:
        ir->opcode = rv_insn_slti;
        return true;
    case 3:
        ir->opcode = rv_insn_sltiu;
        return true;
    case 4:
        ir->opcode = rv_insn_xori;
        return true;
    case 5:
        switch ((insn >> 20) & 0xfff) {
#if RV32_HAS(Zbb)
        case 0x287:
            ir->opcode = rv_insn_orcb;
            return true;
#endif /* RV32_HAS(Zbb) */
#if RV32_HAS(Zbb)
        case 0x698:
            ir->opcode = rv_insn_rev8;
            return true;
#endif /* RV32_HAS(Zbb) */
        default:
            break;
        }
        switch ((insn >> 25) & 0x7f) {
        case 0:
            ir->opcode = rv_insn_srli;
            return true;
        case 0x20:
            ir->opcode = rv_insn_srai;
            return true;
#if RV32_HAS(Zbs)
        case 0x24:
            ir->opcode = rv_insn_bexti;
            return true;
#endif /* RV32_HAS(Zbs) */
#if RV32_HAS(Zbb)
        case 0x30:
            ir->opcode = rv_insn_rori;
            return true;
#endif /* RV32_HAS(Zbb) */
        default:
            break;
        }
        break;
    case 6:
        ir->opcode = rv_insn_ori;
        return true;
    case 7:
        ir->opcode = rv_insn_andi;
        return true;
    default:
        break;
    }
    return false;
}

static inline bool op_auipc(rv_insn_t *ir, const uint32_t insn)
{
    decode_utype(ir, insn);

    /* Any integer computational instruction writing into "x0" is NOP. */
    if (unlikely(ir->rd == rv_reg_zero)) {
        ir->opcode = rv_insn_nop;
        return true;
    }
    ir->opcode = rv_insn_auipc;
    return true;
}

static inline bool op_store(rv_insn_t *ir, const uint32_t insn)
{
    decode_stype(ir, insn);

    switch ((insn >> 12) & 0x7) {
    case 0:
        ir->opcode = rv_insn_sb;
        return true;
    case 1:
        ir->opcode = rv_insn_sh;
        return true;
    case 2:
        ir->opcode = rv_insn_sw;
        return true;
    default:
        break;
    }
    return false;
}

#if RV32_HAS(EXT_F)
static inline bool op_store_fp(rv_insn_t *ir, const uint32_t insn)
{
    decode_stype(ir, insn);

    switch ((insn >> 12) & 0x7) {
#if RV32_HAS(EXT_F)
    case 2:
        ir->opcode = rv_insn_fsw;
        return true;
#endif /* RV32_HAS(EXT_F) */
    default:
        break;
    }
    return false;
}
#else /* !RV32_HAS(EXT_F) */
#define op_store_fp op_unimp
#endif /* RV32_HAS(EXT_F) */

static inline bool op_amo(rv_insn_t *ir, const uint32_t insn)
{
    decode_rtype(ir, insn);

    switch ((insn >> 12) & 0x7) {
    case 2:
        switch ((insn >> 27) & 0x1f) {
#if RV32_HAS(EXT_A)
        case 0:
            ir->opcode = rv_insn_amoaddw;
            return true;
#endif /* RV32_HAS(EXT_A) */
#if RV32_HAS(EXT_A)
        case 1:
            ir->opcode = rv_insn_amoswapw;
            return true;
#endif /* RV32_HAS(EXT_A) */
        case 2:
            switch ((insn >> 20) & 0x1f) {
#if RV32_HAS(EXT_A)
            case 0:
                ir->opcode = rv_insn_lrw;
                return true;
#endif /* RV32_HAS(EXT_A) */
            default:
                break;
            }
            break;
#if RV32_HAS(EXT_A)
        case 3:
            ir->opcode = rv_insn_scw;
            return true;
#endif /* RV32_HAS(EXT_A) */
#if RV32_HAS(EXT_A)
        case 4:
            ir->opcode = rv_insn_amoxorw;
            return true;
#endif /* RV32_HAS(EXT_A) */
#if RV32_HAS(EXT_A)
        case 0x8:
            ir->opcode = rv_insn_amoorw;
            return true;
#endif /* RV32_HAS(EXT_A) */
#if RV32_HAS(EXT_A)
        case 0xc:
            ir->opcode = rv_insn_amoandw;
            return true;
#endif /* RV32_HAS(EXT_A) */
#if RV32_HAS(EXT_A)
        case 0x10:
            ir->opcode = rv_insn_amominw;
            return true;
#endif /* RV32_HAS(EXT_A) */
#if RV32_HAS(EXT_A)
        case 0x14:
            ir->opcode = rv_insn_amomaxw;
            return true;
#endif /* RV32_HAS(EXT_A) */
#if RV32_HAS(EXT_A)
        case 0x18:
            ir->opcode = rv_insn_amominuw;
            return true;
#endif /* RV32_HAS(EXT_A) */
#if RV32_HAS(EXT_A)
        case 0x1c:
            ir->opcode = rv_insn_amomaxuw;
            return true;
#endif /* RV32_HAS(EXT_A) */
        default:
            break;
        }
        break;
    default:
        break;
    }
    return false;
}

static inline bool op_op(rv_insn_t *ir, const uint32_t insn)
{
    decode_rtype(ir, insn);

    /* Any integer computational instruction writing into "x0" is NOP. */
    if (unlikely(ir->rd == rv_reg_zero)) {
        ir->opcode = rv_insn_nop;
        return true;
    }

    switch ((insn >> 12) & 0x7) {
    case 0:
        switch ((insn >> 25) & 0x7f) {
        case 0:
            ir->opcode = rv_insn_add;
            return true;
#if RV32_HAS(EXT_M)
        case 1:
            ir->opcode = rv_insn_mul;
            return true;
#endif /* RV32_HAS(EXT_M) */
        case 0x20:
            ir->opcode = rv_insn_sub;
            return true;
        default:
            break;
        }
        break;
    case 1:
        switch ((insn >> 25) & 0x7f) {
        case 0:
            ir->opcode = rv_insn_sll;
            return true;
#if RV32_HAS(EXT_M)
        case 1:
            ir->opcode = rv_insn_mulh;
            return true;
#endif /* RV32_HAS(EXT_M) */
#if RV32_HAS(Zbc)
        case 5:
            ir->opcode = rv_insn_clmul;
            return true;
#endif /* RV32_HAS(Zbc) */
#if RV32_HAS(Zbs)
        case 0x14:
            ir->opcode = rv_insn_bset;
            return true;
#endif /* RV32_HAS(Zbs) */
#if RV32_HAS(Zbs)
        case 0x24:
            ir->opcode = rv_insn_bclr;
            return true;
#endif /* RV32_HAS(Zbs) */
#if RV32_HAS(Zbb)
        case 0x30:
            ir->opcode = rv_insn_rol;
            return true;
#endif /* RV32_HAS(Zbb) */
#if RV32_HAS(Zbs)
        case 0x34:
            ir->opcode = rv_insn_binv;
            return true;
#endif /* RV32_HAS(Zbs) */
        default:
            break;
        }
        break;
    case 2:
        switch ((insn >> 25) & 0x7f) {
        case 0:
            ir->opcode = rv_insn_slt;
            return true;
#if RV32_HAS(EXT_M)
        case 1:
            ir->opcode = rv_insn_mulhsu;
            return true;
#endif /* RV32_HAS(EXT_M) */
#if RV32_HAS(Zbc)
        case 5:
            ir->opcode = rv_insn_clmulr;
            return true;
#endif /* RV32_HAS(Zbc) */
#if RV32_HAS(Zba)
        case 0x10:
            ir->opcode = rv_insn_sh1add;
            return true;
#endif /* RV32_HAS(Zba) */
        default:
            break;
        }
        break;
    case 3:
        switch ((insn >> 25) & 0x7f) {
        case 0:
            ir->opcode = rv_insn_sltu;
            return true;
#if RV32_HAS(EXT_M)
        case 1:
            ir->opcode = rv_insn_mulhu;
            return true;
#endif /* RV32_HAS(EXT_M) */
#if RV32_HAS(Zbc)
        case 5:
            ir->opcode = rv_insn_clmulh;
            return true;
#endif /* RV32_HAS(Zbc) */
        default:
            break;
        }
        break;
    case 4:
        switch ((insn >> 20) & 0x1f) {
        case 0:
            switch ((insn >> 25) & 0x7f) {
#if RV32_HAS(Zbb)
            case 4:
                ir->opcode = rv_insn_zexth;
                return true;
#endif /* RV32_HAS(Zbb) */
            default:
                break;
            }
            break;
        default:
            break;
        }
        switch ((insn >> 25) & 0x7f) {
        case 0:
            ir->opcode = rv_insn_xor;
            return true;
#if RV32_HAS(EXT_M)
        case 1:
            ir->opcode = rv_insn_div;
            return true;
#endif /* RV32_HAS(EXT_M) */
#if RV32_HAS(Zbb)
        case 5:
            ir->opcode = rv_insn_min;
            return true;
#endif /* RV32_HAS(Zbb) */
#if RV32_HAS(Zba)
        case 0x10:
            ir->opcode = rv_insn_sh2add;
            return true;
#endif /* RV32_HAS(Zba) */
#if RV32_HAS(Zbb)
        case 0x20:
            ir->opcode = rv_insn_xnor;
            return true;
#endif /* RV32_HAS(Zbb) */
        default:
            break;
        }
        break;
    case 5:
        switch ((insn >> 25) & 0x7f) {
        case 0:
            ir->opcode = rv_insn_srl;
            return true;
#if RV32_HAS(EXT_M)
        case 1:
            ir->opcode = rv_insn_divu;
            return true;
#endif /* RV32_HAS(EXT_M) */
#if RV32_HAS(Zbb)
        case 5:
            ir->opcode = rv_insn_minu;
            return true;
#endif /* RV32_HAS(Zbb) */
        case 0x20:
            ir->opcode = rv_insn_sra;
            return true;
#if RV32_HAS(Zbs)
        case 0x24:
            ir->opcode = rv_insn_bext;
            return true;
#endif /* RV32_HAS(Zbs) */
#if RV32_HAS(Zbb)
        case 0x30:
            ir->opcode = rv_insn_ror;
            return true;
#endif /* RV32_HAS(Zbb) */
        default:
            break;
        }
        break;
    case 6:
        switch ((insn >> 25) & 0x7f) {
        case 0:
            ir->opcode = rv_insn_or;
            return true;
#if RV32_HAS(EXT_M)
        case 1:
            ir->opcode = rv_insn_rem;
            return true;
#endif /* RV32_HAS(EXT_M) */
#if RV32_HAS(Zbb)
        case 5:
            ir->opcode = rv_insn_max;
            return true;
#endif /* RV32_HAS(Zbb) */
#if RV32_HAS(Zba)
        case 0x10:
            ir->opcode = rv_insn_sh3add;
            return true;
#endif /* RV32_HAS(Zba) */
#if RV32_HAS(Zbb)
        case 0x20:
            ir->opcode = rv_insn_orn;
            return true;
#endif /* RV32_HAS(Zbb) */
        default:
            break;
        }
        break;
    case 7:
        switch ((insn >> 25) & 0x7f) {
        case 0:
            ir->opcode = rv_insn_and;
            return true;
#if RV32_HAS(EXT_M)
        case 1:
            ir->opcode = rv_insn_remu;
            return true;
#endif /* RV32_HAS(EXT_M) */
#if RV32_HAS(Zbb)
        case 5:
            ir->opcode = rv_insn_maxu;
            return true;
#endif /* RV32_HAS(Zbb) */
#if RV32_HAS(Zbb)
        case 0x20:
            ir->opcode = rv_insn_andn;
            return true;
#endif /* RV32_HAS(Zbb) */
        default:
            break;
        }
        break;
    default:
        break;
    }
    return false;
}

static inline bool op_lui(rv_insn_t *ir, const uint32_t insn)
{
    decode_utype(ir, insn);

    /* Any integer computational instruction writing into "x0" is NOP. */
    if (unlikely(ir->rd == rv_reg_zero)) {
        ir->opcode = rv_insn_nop;
        return true;
    }
    ir->opcode = rv_insn_lui;
    return true;
}

#if RV32_HAS(EXT_F)
static inline bool op_madd(rv_insn_t *ir, const uint32_t insn)
{
    decode_r4type(ir, insn);
    ir->rm = decode_funct3(insn); /* rounding mode */

    switch ((insn >> 25) & 0x3) {
#if RV32_HAS(EXT_F)
    case 0:
        ir->opcode = rv_insn_fmadds;
        return true;
#endif /* RV32_HAS(EXT_F) */
    default:
        break;
    }
    return false;
}
#else /* !RV32_HAS(EXT_F) */
#define op_madd op_unimp
#endif /* RV32_HAS(EXT_F) */

#if RV32_HAS(EXT_F)
static inline bool op_msub(rv_insn_t *ir, const uint32_t insn)
{
    decode_r4type(ir, insn);
    ir->rm = decode_funct3(insn); /* rounding mode */

    switch ((insn >> 25) & 0x3) {
#if RV32_HAS(EXT_F)
    case 0:
        ir->opcode = rv_insn_fmsubs;
        return true;
#endif /* RV32_HAS(EXT_F) */
    default:
        break;
    }
    return false;
}
#else /* !RV32_HAS(EXT_F) */
#define op_msub op_unimp
#endif /* RV32_HAS(EXT_F) */

#if RV32_HAS(EXT_F)
static inline bool op_nmsub(rv_insn_t *ir, const uint32_t insn)
{
    decode_r4type(ir, insn);
    ir->rm = decode_funct3(insn); /* rounding mode */

    switch ((insn >> 25) & 0x3) {
#if RV32_HAS(EXT_F)
    case 0:
        ir->opcode = rv_insn_fnmsubs;
        return true;
#endif /* RV32_HAS(EXT_F) */
    default:
        break;
    }
    return false;
}
#else /* !RV32_HAS(EXT_F) */
#define op_nmsub op_unimp
#endif /* RV32_HAS(EXT_F) */

#if RV32_HAS(EXT_F)
static inline bool op_nmadd(rv_insn_t *ir, const uint32_t insn)
{
    decode_r4type(ir, insn);
    ir->rm = decode_funct3(insn); /* rounding mode */

    switch ((insn >> 25) & 0x3) {
#if RV32_HAS(EXT_F)
    case 0:
        ir->opcode = rv_insn_fnmadds;
        return true;
#endif /* RV32_HAS(EXT_F) */
    default:
        break;
    }
    return false;
}
#else /* !RV32_HAS(EXT_F) */
#define op_nmadd op_unimp
#endif /* RV32_HAS(EXT_F) */

#if RV32_HAS(EXT_F)
static inline bool op_op_fp(rv_insn_t *ir, const uint32_t insn)
{
    decode_rtype(ir, insn);
    ir->rm = decode_funct3(insn); /* rounding mode */

    switch ((insn >> 25) & 0x3) {
    case 0:
        switch ((insn >> 12) & 0x7) {
        case 0:
            switch ((insn >> 27) & 0x1f) {
#if RV32_HAS(EXT_F)
            case 4:
                ir->opcode = rv_insn_fsgnjs;
                return true;
#endif /* RV32_HAS(EXT_F) */
#if RV32_HAS(EXT_F)
            case 5:
                ir->opcode = rv_insn_fmins;
                return true;
#endif /* RV32_HAS(EXT_F) */
#if RV32_HAS(EXT_F)
            case 0x14:
                ir->opcode = rv_insn_fles;
                return true;
#endif /* RV32_HAS(EXT_F) */
            case 0x1c:
                switch ((insn >> 20) & 0x1f) {
#if RV32_HAS(EXT_F)
                case 0:
                    ir->opcode = rv_insn_fmvxw;
                    return true;
#endif /* RV32_HAS(EXT_F) */
                default:
                    break;
                }
                break;
            case 0x1e:
                switch ((insn >> 20) & 0x1f) {
#if RV32_HAS(EXT_F)
                case 0:
                    ir->opcode = rv_insn_fmvwx;
                    return true;
#endif /* RV32_HAS(EXT_F) */
                default:
                    break;
                }
                break;
            default:
                break;
            }
            break;
        case 1:
            switch ((insn >> 27) & 0x1f) {
#if RV32_HAS(EXT_F)
            case 4:
                ir->opcode = rv_insn_fsgnjns;
                return true;
#endif /* RV32_HAS(EXT_F) */
#if RV32_HAS(EXT_F)
            case 5:
                ir->opcode = rv_insn_fmaxs;
                return true;
#endif /* RV32_HAS(EXT_F) */
#if RV32_HAS(EXT_F)
            case 0x14:
                ir->opcode = rv_insn_flts;
                return true;
#endif /* RV32_HAS(EXT_F) */
            case 0x1c:
                switch ((insn >> 20) & 0x1f) {
#if RV32_HAS(EXT_F)
                case 0:
                    ir->opcode = rv_insn_fclasss;
                    return true;
#endif /* RV32_HAS(EXT_F) */
                default:
                    break;
                }
                break;
            default:
                break;
            }
            break;
        case 2:
            switch ((insn >> 27) & 0x1f) {
#if RV32_HAS(EXT_F)
            case 4:
                ir->opcode = rv_insn_fsgnjxs;
                return true;
#endif /* RV32_HAS(EXT_F) */
#if RV32_HAS(EXT_F)
            case 0x14:
                ir->opcode = rv_insn_feqs;
                return true;
#endif /* RV32_HAS(EXT_F) */
            default:
                break;
            }
            break;
        default:
            break;
        }
        switch ((insn >> 27) & 0x1f) {
#if RV32_HAS(EXT_F)
        case 0:
            ir->opcode = rv_insn_fadds;
            return true;
#endif /* RV32_HAS(EXT_F) */
#if RV32_HAS(EXT_F)
        case 1:
            ir->opcode = rv_insn_fsubs;
            return true;
#endif /* RV32_HAS(EXT_F) */
#if RV32_HAS(EXT_F)
        case 2:
            ir->opcode = rv_insn_fmuls;
            return true;
#endif /* RV32_HAS(EXT_F) */
#if RV32_HAS(EXT_F)
        case 3:
            ir->opcode = rv_insn_fdivs;
            return true;
#endif /* RV32_HAS(EXT_F) */
        case 0xb:
            switch ((insn >> 20) & 0x1f) {
#if RV32_HAS(EXT_F)
            case 0:
                ir->opcode = rv_insn_fsqrts;
                return true;
#endif /* RV32_HAS(EXT_F) */
            default:
                break;
            }
            break;
        case 0x18:
            switch ((insn >> 20) & 0x1f) {
#if RV32_HAS(EXT_F)
            case 0:
                ir->opcode = rv_insn_fcvtws;
                return true;
#endif /* RV32_HAS(EXT_F) */
#if RV32_HAS(EXT_F)
            case 1:
                ir->opcode = rv_insn_fcvtwus;
                return true;
#endif /* RV32_HAS(EXT_F) */
            default:
                break;
            }
            break;
        case 0x1a:
            switch ((insn >> 20) & 0x1f) {
#if RV32_HAS(EXT_F)
            case 0:
                ir->opcode = rv_insn_fcvtsw;
                return true;
#endif /* RV32_HAS(EXT_F) */
#if RV32_HAS(EXT_F)
            case 1:
                ir->opcode = rv_insn_fcvtswu;
                return true;
#endif /* RV32_HAS(EXT_F) */
            default:
                break;
            }
            break;
        default:
            break;
        }
        break;
    default:
        break;
    }
    return false;
}
#else /* !RV32_HAS(EXT_F) */
#define op_op_fp op_unimp
#endif /* RV32_HAS(EXT_F) */

static inline bool op_branch(rv_insn_t *ir, const uint32_t insn)
{
    decode_btype(ir, insn);

    switch ((insn >> 12) & 0x7) {
    case 0:
        ir->opcode = rv_insn_beq;
        return true;
    case 1:
        ir->opcode = rv_insn_bne;
        return true;
    case 4:
        ir->opcode = rv_insn_blt;
        return true;
    case 5:
        ir->opcode = rv_insn_bge;
        return true;
    case 6:
        ir->opcode = rv_insn_bltu;
        return true;
    case 7:
        ir->opcode = rv_insn_bgeu;
        return true;
    default:
        break;
    }
    return false;
}

static inline bool op_jalr(rv_insn_t *ir, const uint32_t insn)
{
    decode_itype(ir, insn);

    switch ((insn >> 12) & 0x7) {
    case 0:
        ir->opcode = rv_insn_jalr;
        return true;
    default:
        break;
    }
    return false;
}

static inline bool op_jal(rv_insn_t *ir, const uint32_t insn)
{
    decode_jtype(ir, insn);
    ir->opcode = rv_insn_jal;
    return true;
}

static inline bool op_system(rv_insn_t *ir, const uint32_t insn)
{
    decode_itype(ir, insn);

    switch ((insn >> 7) & 0x1f) {
    case 0:
        switch ((insn >> 12) & 0x7) {
        case 0:
            switch ((insn >> 25) & 0x7f) {
            case 0x9:
                ir->opcode = rv_insn_sfencevma;
                return true;
            default:
                break;
            }
            break;
        default:
            break;
        }
        break;
    default:
        break;
    }
    switch ((insn >> 12) & 0x7) {
    case 0:
        switch ((insn >> 20) & 0xfff) {
        case 0:
            switch ((insn >> 15) & 0x1f) {
            case 0:
                switch ((insn >> 7) & 0x1f) {
                case 0:
                    ir->opcode = rv_insn_ecall;
                    return true;
                default:
                    break;
                }
                break;
            default:
                break;
            }
            break;
        case 1:
            switch ((insn >> 15) & 0x1f) {
            case 0:
                switch ((insn >> 7) & 0x1f) {
                case 0:
                    ir->opcode = rv_insn_ebreak;
                    return true;
                default:
                    break;
                }
                break;
            default:
                break;
            }
            break;
        case 2:
            switch ((insn >> 15) & 0x1f) {
            case 0:
                switch ((insn >> 7) & 0x1f) {
                case 0:
                    ir->opcode = rv_insn_uret;
                    return true;
                default:
                    break;
                }
                break;
            default:
                break;
            }
            break;
        case 0x102:
            switch ((insn >> 15) & 0x1f) {
            case 0:
                switch ((insn >> 7) & 0x1f) {
#if RV32_HAS(SYSTEM)
                case 0:
                    ir->opcode = rv_insn_sret;
                    return true;
#endif /* RV32_HAS(SYSTEM) */
                default:
                    break;
                }
                break;
            default:
                break;
            }
            break;
        case 0x105:
            switch ((insn >> 15) & 0x1f) {
            case 0:
                switch ((insn >> 7) & 0x1f) {
                case 0:
                    ir->opcode = rv_insn_wfi;
                    return true;
                default:
                    break;
                }
                break;
            default:
                break;
            }
            break;
        case 0x202:
            switch ((insn >> 15) & 0x1f) {
            case 0:
                switch ((insn >> 7) & 0x1f) {
                case 0:
                    ir->opcode = rv_insn_hret;
                    return true;
                default:
                    break;
                }
                break;
            default:
                break;
            }
            break;
        case 0x302:
            switch ((insn >> 15) & 0x1f) {
            case 0:
                switch ((insn >> 7) & 0x1f) {
                case 0:
                    ir->opcode = rv_insn_mret;
                    return true;
                default:
                    break;
                }
                break;
            default:
                break;
            }
            break;
        default:
            break;
        }
        break;
#if RV32_HAS(Zicsr)
    case 1:
        ir->opcode = rv_insn_csrrw;
        return true;
#endif /* RV32_HAS(Zicsr) */
#if RV32_HAS(Zicsr)
    case 2:
        ir->opcode = rv_insn_csrrs;
        return true;
#endif /* RV32_HAS(Zicsr) */
#if RV32_HAS(Zicsr)
    case 3:
        ir->opcode = rv_insn_csrrc;
        return true;
#endif /* RV32_HAS(Zicsr) */
#if RV32_HAS(Zicsr)
    case 5:
        ir->opcode = rv_insn_csrrwi;
        return true;
#endif /* RV32_HAS(Zicsr) */
#if RV32_HAS(Zicsr)
    case 6:
        ir->opcode = rv_insn_csrrsi;
        return true;
#endif /* RV32_HAS(Zicsr) */
#if RV32_HAS(Zicsr)
    case 7:
        ir->opcode = rv_insn_csrrci;
        return true;
#endif /* RV32_HAS(Zicsr) */
    default:
        break;
    }
    return csr_is_writable(ir->imm) || (ir->rs1 == rv_reg_zero);
}

#if RV32_HAS(EXT_C)

/* RVC field decoders */
static inline uint16_t c_decode_rs1(const uint16_t insn)
{
    return (insn >> 7) & 0x1f;
}
static inline uint16_t c_decode_rs2(const uint16_t insn)
{
    return (insn >> 2) & 0x1f;
}
static inline uint16_t c_decode_rd(const uint16_t insn)
{
    return (insn >> 7) & 0x1f;
}
static inline uint16_t c_decode_rs1c(const uint16_t insn)
{
    return (insn >> 7) & 0x7;
}
static inline uint16_t c_decode_rs2c(const uint16_t insn)
{
    return (insn >> 2) & 0x7;
}
static inline uint16_t c_decode_rdc(const uint16_t insn)
{
    return (insn >> 2) & 0x7;
}

static inline bool op_rvc_q0(rv_insn_t *ir, const uint32_t insn)
{
    switch ((insn >> 13) & 0x7) {
#if RV32_HAS(EXT_C)
    case 0:
        ir->rd = c_decode_rdc(insn) | 0x08;
        ir->imm = ((insn & 0x1800) >> 7) | ((insn & 0x0780) >> 1) |
                  ((insn & 0x0040) >> 4) | ((insn & 0x0020) >> 2);
        ir->rs1 = rv_reg_sp;
        ir->opcode = rv_insn_caddi4spn;
        return true;
#endif /* RV32_HAS(EXT_C) */
#if RV32_HAS(EXT_C)
    case 2:
        ir->rd = c_decode_rdc(insn) | 0x08;
        ir->rs1 = c_decode_rs1c(insn) | 0x08;
        ir->imm = ((insn & 0x1C00) >> 7) | ((insn & 0x0040) >> 4) |
                  ((insn & 0x0020) << 1);
        ir->opcode = rv_insn_clw;
        return true;
#endif /* RV32_HAS(EXT_C) */
#if RV32_HAS(EXT_F)
    case 3:
        ir->rd = c_decode_rdc(insn) | 0x08;
        ir->rs1 = c_decode_rs1c(insn) | 0x08;
        ir->imm = ((insn & 0x1C00) >> 7) | ((insn & 0x0040) >> 4) |
                  ((insn & 0x0020) << 1);
        ir->opcode = rv_insn_cflw;
        return true;
#endif /* RV32_HAS(EXT_F) */
#if RV32_HAS(EXT_C)
    case 6:
        ir->rs1 = c_decode_rs1c(insn) | 0x08;
        ir->rs2 = c_decode_rs2c(insn) | 0x08;
        ir->imm = ((insn & 0x1C00) >> 7) | ((insn & 0x0040) >> 4) |
                  ((insn & 0x0020) << 1);
        ir->opcode = rv_insn_csw;
        return true;
#endif /* RV32_HAS(EXT_C) */
#if RV32_HAS(EXT_F)
    case 7:
        ir->rs1 = c_decode_rs1c(insn) | 0x08;
        ir->rs2 = c_decode_rs2c(insn) | 0x08;
        ir->imm = ((insn & 0x1C00) >> 7) | ((insn & 0x0040) >> 4) |
                  ((insn & 0x0020) << 1);
        ir->opcode = rv_insn_cfsw;
        return true;
#endif /* RV32_HAS(EXT_F) */
    default:
        break;
    }
    return false;
}

static inline bool op_rvc_q1(rv_insn_t *ir, const uint32_t insn)
{
    switch ((insn >> 2) & 0x1f) {
    case 0:
        switch ((insn >> 7) & 0x1f) {
        case 0:
            switch ((insn >> 12) & 0x1) {
            case 0:
                switch ((insn >> 13) & 0x7) {
#if RV32_HAS(EXT_C)
                case 0:
                    ir->rd = rv_reg_zero;
                    ir->rs1 = rv_reg_zero;
                    ir->opcode = rv_insn_cnop;
                    return true;
#endif /* RV32_HAS(EXT_C) */
                default:
                    break;
                }
                break;
            default:
                break;
            }
            break;
        default:
            break;
        }
        break;
    default:
        break;
    }
    switch ((insn >> 5) & 0x3) {
    case 0:
        switch ((insn >> 10) & 0x3) {
        case 3:
            switch ((insn >> 12) & 0x1) {
            case 0:
                switch ((insn >> 13) & 0x7) {
#if RV32_HAS(EXT_C)
                case 4:
                    ir->rs1 = c_decode_rs1c(insn) | 0x08;
                    ir->rs2 = c_decode_rs2c(insn) | 0x08;
                    ir->rd = ir->rs1;
                    ir->opcode = rv_insn_csub;
                    return true;
#endif /* RV32_HAS(EXT_C) */
                default:
                    break;
                }
                break;
            default:
                break;
            }
            break;
        default:
            break;
        }
        break;
    case 1:
        switch ((insn >> 10) & 0x3) {
        case 3:
            switch ((insn >> 12) & 0x1) {
            case 0:
                switch ((insn >> 13) & 0x7) {
#if RV32_HAS(EXT_C)
                case 4:
                    ir->rs1 = c_decode_rs1c(insn) | 0x08;
                    ir->rs2 = c_decode_rs2c(insn) | 0x08;
                    ir->rd = ir->rs1;
                    ir->opcode = rv_insn_cxor;
                    return true;
#endif /* RV32_HAS(EXT_C) */
                default:
                    break;
                }
                break;
            default:
                break;
            }
            break;
        default:
            break;
        }
        break;
    case 2:
        switch ((insn >> 10) & 0x3) {
        case 3:
            switch ((insn >> 12) & 0x1) {
            case 0:
                switch ((insn >> 13) & 0x7) {
#if RV32_HAS(EXT_C)
                case 4:
                    ir->rs1 = c_decode_rs1c(insn) | 0x08;
                    ir->rs2 = c_decode_rs2c(insn) | 0x08;
                    ir->rd = ir->rs1;
                    ir->opcode = rv_insn_cor;
                    return true;
#endif /* RV32_HAS(EXT_C) */
                default:
                    break;
                }
                break;
            default:
                break;
            }
            break;
        default:
            break;
        }
        break;
    case 3:
        switch ((insn >> 10) & 0x3) {
        case 3:
            switch ((insn >> 12) & 0x1) {
            case 0:
                switch ((insn >> 13) & 0x7) {
#if RV32_HAS(EXT_C)
                case 4:
                    ir->rs1 = c_decode_rs1c(insn) | 0x08;
                    ir->rs2 = c_decode_rs2c(insn) | 0x08;
                    ir->rd = ir->rs1;
                    ir->opcode = rv_insn_cand;
                    return true;
#endif /* RV32_HAS(EXT_C) */
                default:
                    break;
                }
                break;
            default:
                break;
            }
            break;
        default:
            break;
        }
        break;
    default:
        break;
    }
    switch ((insn >> 7) & 0x1f) {
    case 2:
        switch ((insn >> 13) & 0x7) {
#if RV32_HAS(EXT_C)
        case 3:
            ir->imm = ((insn & 0x0040) >> 2) | ((insn & 0x0020) << 1) |
                      ((insn & 0x0018) << 4) | ((insn & 0x0004) << 3) |
                      ((insn & 0x1000) >> 3);
            ir->imm |= -(ir->imm & 0x200);
            ir->rd = rv_reg_sp;
            ir->rs1 = rv_reg_sp;
            ir->opcode = rv_insn_caddi16sp;
            return true;
#endif /* RV32_HAS(EXT_C) */
        default:
            break;
        }
        break;
    default:
        break;
    }
    switch ((insn >> 10) & 0x3) {
    case 0:
        switch ((insn >> 13) & 0x7) {
#if RV32_HAS(EXT_C)
        case 4:
            ir->rs1 = c_decode_rs1c(insn) | 0x08;
            ir->shamt = ((insn >> 7) & 0x20) | ((insn >> 2) & 0x1f);
            ir->imm = ir->shamt;
            ir->rd = ir->rs1;
            ir->opcode = rv_insn_csrli;
            return true;
#endif /* RV32_HAS(EXT_C) */
        default:
            break;
        }
        break;
    case 1:
        switch ((insn >> 13) & 0x7) {
#if RV32_HAS(EXT_C)
        case 4:
            ir->rs1 = c_decode_rs1c(insn) | 0x08;
            ir->shamt = ((insn >> 7) & 0x20) | ((insn >> 2) & 0x1f);
            ir->imm = ir->shamt;
            ir->rd = ir->rs1;
            ir->opcode = rv_insn_csrai;
            return true;
#endif /* RV32_HAS(EXT_C) */
        default:
            break;
        }
        break;
    case 2:
        switch ((insn >> 13) & 0x7) {
#if RV32_HAS(EXT_C)
        case 4:
            ir->rs1 = c_decode_rs1c(insn) | 0x08;
            ir->imm = ((insn >> 2) & 0x1f) | ((insn & 0x1000) >> 7);
            ir->imm |= -(ir->imm & 0x20);
            ir->rd = ir->rs1;
            ir->opcode = rv_insn_candi;
            return true;
#endif /* RV32_HAS(EXT_C) */
        default:
            break;
        }
        break;
    default:
        break;
    }
    switch ((insn >> 13) & 0x7) {
#if RV32_HAS(EXT_C)
    case 0:
        ir->rd = c_decode_rd(insn);
        ir->rs1 = ir->rd;
        ir->imm = ((insn >> 2) & 0x1f) | ((insn & 0x1000) >> 7);
        ir->imm |= -(ir->imm & 0x20);
        if (unlikely(ir->rd == rv_reg_zero)) {
            ir->opcode = rv_insn_cnop;
            return true;
        }
        ir->opcode = rv_insn_caddi;
        return true;
#endif /* RV32_HAS(EXT_C) */
#if RV32_HAS(EXT_C)
    case 1:
        ir->imm = ((insn & 0x0800) >> 7) | ((insn & 0x0600) >> 1) |
                  ((insn & 0x0100) << 2) | ((insn & 0x0080) >> 1) |
                  ((insn & 0x0040) << 1) | ((insn & 0x0038) >> 2) |
                  ((insn & 0x0004) << 3) | ((insn & 0x1000) >> 1);
        ir->imm |= -(ir->imm & 0x800);
        ir->rd = rv_reg_ra;
        ir->opcode = rv_insn_cjal;
        return true;
#endif /* RV32_HAS(EXT_C) */
#if RV32_HAS(EXT_C)
    case 2:
        ir->rd = c_decode_rd(insn);
        ir->imm = ((insn >> 2) & 0x1f) | ((insn & 0x1000) >> 7);
        ir->imm |= -(ir->imm & 0x20);
        ir->rs1 = rv_reg_zero;
        if (unlikely(ir->rd == rv_reg_zero)) {
            ir->opcode = rv_insn_cnop;
            return true;
        }
        ir->opcode = rv_insn_cli;
        return true;
#endif /* RV32_HAS(EXT_C) */
#if RV32_HAS(EXT_C)
    case 3:
        ir->rd = c_decode_rd(insn);
        ir->imm = ((insn >> 2) & 0x1f) | ((insn & 0x1000) >> 7);
        ir->imm |= -(ir->imm & 0x20);
        ir->imm <<= 12;
        if (unlikely(ir->rd == rv_reg_zero)) {
            ir->opcode = rv_insn_cnop;
            return true;
        }
        ir->opcode = rv_insn_clui;
        return true;
#endif /* RV32_HAS(EXT_C) */
#if RV32_HAS(EXT_C)
    case 5:
        ir->imm = ((insn & 0x0800) >> 7) | ((insn & 0x0600) >> 1) |
                  ((insn & 0x0100) << 2) | ((insn & 0x0080) >> 1) |
                  ((insn & 0x0040) << 1) | ((insn & 0x0038) >> 2) |
                  ((insn & 0x0004) << 3) | ((insn & 0x1000) >> 1);
        ir->imm |= -(ir->imm & 0x800);
        ir->rd = rv_reg_zero;
        ir->opcode = rv_insn_cj;
        return true;
#endif /* RV32_HAS(EXT_C) */
#if RV32_HAS(EXT_C)
    case 6:
        ir->rs1 = c_decode_rs1c(insn) | 0x08;
        ir->imm = ((insn & 0x0C00) >> 7) | ((insn & 0x0060) << 1) |
                  ((insn & 0x0018) >> 2) | ((insn & 0x0004) << 3) |
                  ((insn & 0x1000) >> 4);
        ir->imm |= -(ir->imm & 0x100);
        ir->rs2 = rv_reg_zero;
        ir->opcode = rv_insn_cbeqz;
        return true;
#endif /* RV32_HAS(EXT_C) */
#if RV32_HAS(EXT_C)
    case 7:
        ir->rs1 = c_decode_rs1c(insn) | 0x08;
        ir->imm = ((insn & 0x0C00) >> 7) | ((insn & 0x0060) << 1) |
                  ((insn & 0x0018) >> 2) | ((insn & 0x0004) << 3) |
                  ((insn & 0x1000) >> 4);
        ir->imm |= -(ir->imm & 0x100);
        ir->rs2 = rv_reg_zero;
        ir->opcode = rv_insn_cbnez;
        return true;
#endif /* RV32_HAS(EXT_C) */
    default:
        break;
    }
    return false;
}

static inline bool op_rvc_q2(rv_insn_t *ir, const uint32_t insn)
{
    switch ((insn >> 2) & 0x1f) {
    case 0:
        switch ((insn >> 7) & 0x1f) {
        case 0:
            switch ((insn >> 12) & 0x1) {
            case 1:
                switch ((insn >> 13) & 0x7) {
#if RV32_HAS(EXT_C)
                case 4:
                    ir->opcode = rv_insn_cebreak;
                    return true;
#endif /* RV32_HAS(EXT_C) */
                default:
                    break;
                }
                break;
            default:
                break;
            }
            break;
        default:
            break;
        }
        switch ((insn >> 12) & 0x1) {
        case 0:
            switch ((insn >> 13) & 0x7) {
#if RV32_HAS(EXT_C)
            case 4:
                ir->rs1 = c_decode_rs1(insn);
                ir->rd = rv_reg_zero;
                ir->opcode = rv_insn_cjr;
                return true;
#endif /* RV32_HAS(EXT_C) */
            default:
                break;
            }
            break;
        case 1:
            switch ((insn >> 13) & 0x7) {
#if RV32_HAS(EXT_C)
            case 4:
                ir->rs1 = c_decode_rs1(insn);
                ir->rd = rv_reg_ra;
                ir->opcode = rv_insn_cjalr;
                return true;
#endif /* RV32_HAS(EXT_C) */
            default:
                break;
            }
            break;
        default:
            break;
        }
        break;
    default:
        break;
    }
    switch ((insn >> 12) & 0x1) {
    case 0:
        switch ((insn >> 13) & 0x7) {
#if RV32_HAS(EXT_C)
        case 4:
            ir->rd = c_decode_rd(insn);
            ir->rs2 = c_decode_rs2(insn);
            ir->rs1 = rv_reg_zero;
            if (unlikely(ir->rd == rv_reg_zero)) {
                ir->opcode = rv_insn_cnop;
                return true;
            }
            ir->opcode = rv_insn_cmv;
            return true;
#endif /* RV32_HAS(EXT_C) */
        default:
            break;
        }
        break;
    case 1:
        switch ((insn >> 13) & 0x7) {
#if RV32_HAS(EXT_C)
        case 4:
            ir->rd = c_decode_rd(insn);
            ir->rs1 = ir->rd;
            ir->rs2 = c_decode_rs2(insn);
            if (unlikely(ir->rd == rv_reg_zero)) {
                ir->opcode = rv_insn_cnop;
                return true;
            }
            ir->opcode = rv_insn_cadd;
            return true;
#endif /* RV32_HAS(EXT_C) */
        default:
            break;
        }
        break;
    default:
        break;
    }
    switch ((insn >> 13) & 0x7) {
#if RV32_HAS(EXT_C)
    case 0:
        ir->rd = c_decode_rd(insn);
        ir->rs1 = ir->rd;
        ir->shamt = ((insn >> 7) & 0x20) | ((insn >> 2) & 0x1f);
        ir->imm = ir->shamt;
        if (unlikely(ir->rd == rv_reg_zero)) {
            ir->opcode = rv_insn_cnop;
            return true;
        }
        ir->opcode = rv_insn_cslli;
        return true;
#endif /* RV32_HAS(EXT_C) */
#if RV32_HAS(EXT_C)
    case 2:
        ir->rd = c_decode_rd(insn);
        ir->imm = ((insn & 0x1000) >> 7) | ((insn & 0x0070) >> 2) |
                  ((insn & 0x000C) << 4);
        ir->rs1 = rv_reg_sp;
        if (unlikely(ir->rd == rv_reg_zero))
            return false;
        ir->opcode = rv_insn_clwsp;
        return true;
#endif /* RV32_HAS(EXT_C) */
#if RV32_HAS(EXT_F)
    case 3:
        ir->rd = c_decode_rd(insn);
        ir->imm = ((insn & 0x1000) >> 7) | ((insn & 0x0070) >> 2) |
                  ((insn & 0x000C) << 4);
        ir->rs1 = rv_reg_sp;
        ir->opcode = rv_insn_cflwsp;
        return true;
#endif /* RV32_HAS(EXT_F) */
#if RV32_HAS(EXT_C)
    case 6:
        ir->rs2 = c_decode_rs2(insn);
        ir->imm = ((insn & 0x1E00) >> 7) | ((insn & 0x0180) >> 1);
        ir->rs1 = rv_reg_sp;
        ir->opcode = rv_insn_cswsp;
        return true;
#endif /* RV32_HAS(EXT_C) */
#if RV32_HAS(EXT_F)
    case 7:
        ir->rs2 = c_decode_rs2(insn);
        ir->imm = ((insn & 0x1E00) >> 7) | ((insn & 0x0180) >> 1);
        ir->rs1 = rv_reg_sp;
        ir->opcode = rv_insn_cfswsp;
        return true;
#endif /* RV32_HAS(EXT_F) */
    default:
        break;
    }
    return false;
}

#endif /* RV32_HAS(EXT_C) */

static inline bool op_unimp(rv_insn_t *ir UNUSED, uint32_t insn UNUSED)
{
    return false;
}

typedef bool (*decode_t)(rv_insn_t *ir, uint32_t insn);

static const decode_t rv_jump_table[] = {
    op_load,     /* 0 */
    op_load_fp,  /* 1 */
    op_unimp,    /* 2 */
    op_misc_mem, /* 3 */
    op_op_imm,   /* 4 */
    op_auipc,    /* 5 */
    op_unimp,    /* 6 */
    op_unimp,    /* 7 */
    op_store,    /* 8 */
    op_store_fp, /* 9 */
    op_unimp,    /* 10 */
    op_amo,      /* 11 */
    op_op,       /* 12 */
    op_lui,      /* 13 */
    op_unimp,    /* 14 */
    op_unimp,    /* 15 */
    op_madd,     /* 16 */
    op_msub,     /* 17 */
    op_nmsub,    /* 18 */
    op_nmadd,    /* 19 */
    op_op_fp,    /* 20 */
    op_unimp,    /* 21 */
    op_unimp,    /* 22 */
    op_unimp,    /* 23 */
    op_branch,   /* 24 */
    op_jalr,     /* 25 */
    op_unimp,    /* 26 */
    op_jal,      /* 27 */
    op_system,   /* 28 */
    op_unimp,    /* 29 */
    op_unimp,    /* 30 */
    op_unimp,    /* 31 */
};

#if RV32_HAS(EXT_C)
static const decode_t rvc_jump_table[] = {
    op_rvc_q0, op_rvc_q1, op_rvc_q2, op_unimp, /* funct3=0 */
    op_rvc_q0, op_rvc_q1, op_rvc_q2, op_unimp, /* funct3=1 */
    op_rvc_q0, op_rvc_q1, op_rvc_q2, op_unimp, /* funct3=2 */
    op_rvc_q0, op_rvc_q1, op_rvc_q2, op_unimp, /* funct3=3 */
    op_rvc_q0, op_rvc_q1, op_rvc_q2, op_unimp, /* funct3=4 */
    op_rvc_q0, op_rvc_q1, op_rvc_q2, op_unimp, /* funct3=5 */
    op_rvc_q0, op_rvc_q1, op_rvc_q2, op_unimp, /* funct3=6 */
    op_rvc_q0, op_rvc_q1, op_rvc_q2, op_unimp, /* funct3=7 */
};
#endif /* RV32_HAS(EXT_C) */

bool rv_decode(rv_insn_t *ir, uint32_t insn)
{
    bool ret;
    assert(ir);

#if RV32_HAS(EXT_C)
    if (is_compressed(insn)) {
        insn &= 0x0000FFFF;
        const uint16_t c_index = ((insn & 0xE000) >> 11) | (insn & 0x3);
        ret = rvc_jump_table[c_index](ir, insn);
        goto end;
    }
#endif

    const uint32_t index = (insn >> 2) & 0x1f;
    ret = rv_jump_table[index](ir, insn);

end:

#if RV32_HAS(RV32E)
    if (unlikely(ir->rd > 15 || ir->rs1 > 15 || ir->rs2 > 15))
        ret = false;
#endif

    return ret;
}
