/* RV32 RVV Instruction Set */

#define SCALAR_TO_VEC(scalar, vvec_idx, bit) for (int i = 0; i < rv.vl; i++) { rv->V[vvec_idx] = scalar; }

RVOP(vadd_vi, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vadd_vv, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vand_vi, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vand_vv, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vmadc_vi, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vmadc_vv, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vmseq_vi, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vmseq_vv, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vmsgt_vi, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vmsgt_vv, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vmsgtu_vi, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vmsgtu_vv, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vmsle_vi, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vmsle_vv, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vmsleu_vi, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vmsleu_vv, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vmsne_vi, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vmsne_vv, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vor_vi, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vor_vv, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vrgather_vi, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vrgather_vv, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vrsub_vi, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vrsub_vv, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vsadd_vi, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vsadd_vv, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vsaddu_vi, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vsaddu_vv, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vslidedown_vi, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vslidedown_vv, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vslideup_vi, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vslideup_vv, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vsll_vi, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vsll_vv, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vsra_vi, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vsra_vv, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vsrl_vi, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vsrl_vv, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vssra_vi, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vssra_vv, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vssrl_vi, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vssrl_vv, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vxor_vi, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
RVOP(vxor_vv, { rv->V[rv_reg_zero] = 0; }, GEN({/* no operation */}))
